# version: 'version'
services:
  # app:
  #   build:
  #     context: app
  #   env_file:
  #     - app&backend.env
  #     - common.env
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   restart: unless-stopped
    
  db:
    image: mysql:latest
    env_file:
      - common.env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db-data:/var/lib/mysql
    restart: always

  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   env_file:
  #     - phpmyadmin.env
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - db
  #   restart: always

  backend:
    build:
      context: backend
    ports:
      - "5000:80"
    env_file:
      - app&backend.env
      - common.env
    restart: always

  # reverse_proxy:
  #   build:
  #     context: reverseproxy
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   restart: always
  #   volumes:
  #     - frontend-files:/usr/local/apache2/htdocs
volumes:
  db-data:
  frontend-files: